### ISSUE TITLE
Can't fetch any page from Wikidot

### ISSUE THREAD

**Issue by LajterPL** [Zokhoi/vscode-ftml#2]
I just installed the extension and tried to fetch any page from different sites and I can't make it work, because I get "The remote page does not exist on site" error

Example:
![](https://i.imgur.com/pbQC5Ht.png)

**Comment by Zokhoi** [comment]
This bug is identified for using the command in triple dot menu, and is fixed in fc177d7. The next release will ship the fix.

Meanwhile, please use Ctrl+Shift+P to bring up command palette and search for "ftml fetch", and invoke the command from there.

**Comment by Zokhoi** [comment]
Release 0.1.1 is now published on extension marketplace. Please update to the version for the fix.

**Comment by LajterPL** [comment]
Thank you, it's working now
