### ISSUE TITLE
Arguments in [[module css]] causes CSS highlighting to fail

### ISSUE THREAD

**Issue by ghostchibi** [Zokhoi/vscode-ftml#3]
CSS highlighting on code inside of a `[[module css]]` fails when using arguments for the module. `show="true"` and `disable="true"` should be accepted arguments.
http://www.wikidot.com/doc-modules:css-module

CSS highlighting working for `[[module css]]` without any arguments:
![image](https://github.com/Zokhoi/vscode-ftml/assets/61921017/07a4d85b-d186-43c8-bc47-830e7e2b8116)

Using `show="true"` argument, which causes highlighting to fail:
![image](https://github.com/Zokhoi/vscode-ftml/assets/61921017/754a595b-002e-4b69-8fea-896b98cc845f)

**Comment by Zokhoi** [comment]
Extension version 0.2.4 is published onto the marketplace, which should fix this. Let me know if something still isn't working.

**Comment by ghostchibi** [comment]
Works like charm :)
